version: "3.8"

services:
  # --------------------------------------------------
  # Infrastructure Services
  # --------------------------------------------------
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: soccer_quiz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - soccer_quiz_net

  mongo-db:
    image: mongo:5.0
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - soccer_quiz_net

  # --------------------------------------------------
  # Backend Microservices
  # --------------------------------------------------
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000" # Main entry point for the frontend
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_URL=http://user-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
      - QUIZ_SERVICE_URL=http://quiz-service:3000
    depends_on:
      - user-service
      - auth-service
      - quiz-service
    networks:
      - soccer_quiz_net

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://admin:${POSTGRES_PASSWORD}@postgres-db:5432/soccer_quiz?schema=public"
    depends_on:
      - postgres-db
    networks:
      - soccer_quiz_net

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: "postgresql://admin:${POSTGRES_PASSWORD}@postgres-db:5432/soccer_quiz?schema=public"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres-db
    networks:
      - soccer_quiz_net

  quiz-service:
    build: ./backend/quiz-service
    container_name: quiz-service
    ports:
      - "3003:3000"
    environment:
      MONGO_URI: "mongodb://root:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/soccer_quiz?authSource=admin"
    depends_on:
      - mongo-db
    networks:
      - soccer_quiz_net

volumes:
  postgres_data:
  mongo_data:

networks:
  soccer_quiz_net:
    driver: bridge
