version: "3.9"

services:
  # ======================
  # Infraestrutura Base

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # protocolo AMQP
      - "15672:15672" # painel web
    networks:
      - backend-network

  # ========================================================================================================================
  #  Microserviços NestJS

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - team-service
      - question-service
      - answer-service
      - rabbitmq
    environment:
      JWT_SECRET: "super-secret"
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/auth_db
      JWT_SECRET: "super-secret"
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/user_db
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

  team-service:
    build: ./team-service
    container_name: team-service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/team_db
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

  question-service:
    build: ./question-service
    container_name: question-service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URL: mongodb://mongodb:27017/question_db
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

  answer-service:
    build: ./answer-service
    container_name: answer-service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URL: mongodb://mongodb:27017/answer_db
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - backend-network

# ======================
# Volumes persistentes
# ======================
volumes:
  postgres_data:
  mongo_data:

# ======================
# Rede interna
# ======================
networks:
  backend-network:
    driver: bridge
