name: Deploy Auth Service

on:
  push:
    branches: ["main"]
    paths:
      - "backend/auth-service/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          cd backend/auth-service
          pip install -r requirements.txt

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "auth-service-quiz"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: backend/auth-service
