name: Deploy Quiz Microservice

on:
  push:
    branches: ["main"]
    paths:
      - "backend/quiz-service/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          cd backend/quiz-service
          pip install -r requirements.txt

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "quiz-microservice"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: backend/quiz-service
